# -*- coding: utf-8 -*-
"""Notion_ReAct_Planner_Agent_Pipleine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OevXK_U3bG0ei1HPr6S90-HG--hwrRwn

# 🤖 Notion ReAct Planner Agent

A **reasoning-driven daily planning system** powered by a ReAct (Reason + Act) AI agent,
deeply integrated with Notion.

### Architecture Overview
```
User → FastAPI Server → LangChain ReAct Agent → Tool Belt
                              ↑                      ↓
                         Groq LLM            Notion API / Open-Meteo API
```

### Project Structure (mirrored in this notebook)
```
├── Section 1  – Environment Setup & Secrets
├── Section 2  – Install Dependencies
├── Section 3  – Logger Utility          (utils/logger.py)
├── Section 4  – Weather Tool            (tools/weather.py)
├── Section 5  – Notion Notes Tool       (tools/notion_notes.py)
├── Section 6  – Notion Calendar Tool    (tools/notion_calender.py)
├── Section 7  – Agent Core              (agent/bot.py)
├── Section 8  – FastAPI Server          (api/server.py)
├── Section 9  – Notion DB Setup Script  (scripts/setup_notion_databases.py)
├── Section 10 – Agent Testing           (scripts/test_agent.py)
└── Section 11 – Run the Server (ngrok tunnel for Colab)
```

---
## Section 1 — Environment Setup & Secrets

All sensitive keys are loaded from **Colab Secrets** (🔑 icon in the left sidebar).

Required secrets:
| Secret Key | Description |
|---|---|
| `GROQ_API_KEY` | Groq Cloud API key for LLM inference |
| `NOTION_API_KEY` | Notion integration token |
| `NOTION_CALENDAR_DB_ID` | Notion Calendar database ID |
| `NOTION_NOTES_DB_ID` | Notion Notes database ID |
| `MLFLOW_TRACKING_URI` | DagsHub MLflow tracking URI |
| `MLFLOW_TRACKING_USERNAME` | DagsHub username |
| `MLFLOW_TRACKING_PASSWORD` | DagsHub password / token |
"""

import os
from google.colab import userdata

# ── Groq LLM API key ──────────────────────────────────────────────────────────
# Used by the ReAct agent for all LLM inference calls via langchain-groq
os.environ['GROQ_API_KEY'] = userdata.get('GROQ_API_KEY')

# ── Notion API credentials ────────────────────────────────────────────────────
# NOTION_API_KEY      : integration token from https://www.notion.so/my-integrations
# NOTION_CALENDAR_DB_ID : ID of the 'Smart Task Planner Calendar' database
# NOTION_NOTES_DB_ID  : ID of the 'Smart Task Planner Notes' database
os.environ['NOTION_API_KEY']          = userdata.get('NOTION_API_KEY')
os.environ['NOTION_CALENDAR_DB_ID']   = userdata.get('NOTION_CALENDAR_DB_ID')
os.environ['NOTION_NOTES_DB_ID']      = userdata.get('NOTION_NOTES_DB_ID')

# ── MLflow / DagsHub experiment tracking ─────────────────────────────────────
# Set USE_DAGSHUB = True  → logs go to your DagsHub remote MLflow server
# Set USE_DAGSHUB = False → logs go to a local ./mlruns folder inside Colab
USE_DAGSHUB = True

if USE_DAGSHUB:
    # Remote DagsHub MLflow tracking
    os.environ['MLFLOW_TRACKING_URI']      = userdata.get('MLFLOW_TRACKING_URI')
    os.environ['MLFLOW_TRACKING_USERNAME'] = userdata.get('MLFLOW_TRACKING_USERNAME')
    os.environ['MLFLOW_TRACKING_PASSWORD'] = userdata.get('MLFLOW_TRACKING_PASSWORD')
else:
    # Local MLflow — experiment logs saved inside the Colab runtime
    os.environ['MLFLOW_TRACKING_URI'] = f"file://{os.getcwd()}/mlruns"

print('✅ Environment variables set successfully.')
print(f"   MLFLOW_TRACKING_URI = {os.environ['MLFLOW_TRACKING_URI']}")
print(f"   GROQ key starts with: {os.environ['GROQ_API_KEY'][:6]}...")

"""---
## Section 2 — Install Dependencies

Mirrors `requirements.txt` from the project.  
`pyngrok` is added for exposing the FastAPI server through a public tunnel in Colab.
"""

# Install all required packages
# - langchain / langchain-core / langchain-groq : ReAct agent framework + Groq integration
# - fastapi / uvicorn                           : REST API server
# - requests                                    : HTTP calls to Notion & Open-Meteo APIs
# - pyngrok                                     : expose local server to the internet (Colab only)
# - mlflow / dagshub                            : experiment tracking

!pip install -q --upgrade \
    langchain==0.1.16 \
    langchain-core==0.1.16 \
    langchain-groq==0.1.4 \
    fastapi>=0.115.0 \
    "uvicorn[standard]>=0.32.0" \
    requests \
    pyngrok \
    mlflow \
    dagshub

print("✅ All dependencies installed.")

"""---
## Section 3 — Logger Utility
**Mirrors:** `utils/logger.py`

A shared logging factory used by every module to produce consistent,
timestamped log output to stdout.
"""

import logging
import sys

def get_logger(name: str) -> logging.Logger:
    """
    Returns a configured Logger instance for the given module name.

    Ensures that duplicate handlers are not added on repeated calls
    (important in Colab where cells can be re-executed).

    Args:
        name (str): The module or component name, typically __name__.

    Returns:
        logging.Logger: A logger that writes INFO+ messages to stdout
                        with format: <timestamp> - <name> - <level> - <message>
    """
    logger = logging.getLogger(name)

    # Guard against adding multiple handlers when cells are re-run in Colab
    if not logger.handlers:
        logger.setLevel(logging.INFO)

        # Stream to stdout so Colab captures the output in the cell
        handler = logging.StreamHandler(sys.stdout)

        # Human-readable format with timestamp, module, level, and message
        formatter = logging.Formatter(
            '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        )
        handler.setFormatter(formatter)
        logger.addHandler(handler)

    return logger


# ── Quick smoke-test ──────────────────────────────────────────────────────────
test_logger = get_logger("logger_test")
test_logger.info("✅ Logger utility initialised successfully.")

"""---
## Section 4 — Weather Tool
**Mirrors:** `tools/weather.py`

Uses the **Open-Meteo** free public API (no auth required) to fetch current temperature
for any city. The agent calls this tool when the user asks about weather or needs
context-aware planning (e.g., "plan a morning walk if it's sunny").

Flow:
1. Geocoding API → lat/lon from city name
2. Forecast API  → current temperature
"""

import requests
from langchain.tools import tool

@tool
def get_weather(city: str) -> dict:
    """
    Fetches the current temperature for a given city using the Open-Meteo API.

    Two-step process:
      1. Geocode the city name to latitude/longitude coordinates.
      2. Query the weather forecast endpoint for the current temperature.

    Args:
        city (str): Name of the city (e.g. "Delhi", "London").

    Returns:
        dict: {"city": str, "temp": float, "unit": "C"}
              or {"error": str} on failure.
    """
    try:
        # ── Step 1: Geocoding ─────────────────────────────────────────────────
        # Convert city name → latitude & longitude using Open-Meteo's geocoding API
        geo_url = (
            f"https://geocoding-api.open-meteo.com/v1/search"
            f"?name={city}&count=1&language=en&format=json"
        )
        geo_data = requests.get(geo_url).json()

        # If no results returned, the city name is unrecognised
        if not geo_data.get("results"):
            return {"error": f"City '{city}' not found in geocoding database."}

        # Extract coordinates from the first (best-match) result
        location = geo_data["results"][0]
        lat = location["latitude"]
        lon = location["longitude"]

        # ── Step 2: Current Weather ───────────────────────────────────────────
        # Fetch current temperature and weather code at the resolved coordinates
        weather_url = (
            f"https://api.open-meteo.com/v1/forecast"
            f"?latitude={lat}&longitude={lon}"
            f"&current=temperature_2m,weather_code"
        )
        weather_data = requests.get(weather_url).json()

        # temperature_2m is the standard 2-metre air temperature in °C
        temp = weather_data["current"]["temperature_2m"]

        return {"city": city, "temp": temp, "unit": "C"}

    except Exception as e:
        # Return error dict so the agent can communicate failure gracefully
        return {"error": str(e)}


# ── Quick smoke-test ──────────────────────────────────────────────────────────
print("Weather tool test:", get_weather.invoke("Delhi"))

"""---
## Section 5 — Notion Notes Tool
**Mirrors:** `tools/notion_notes.py`

Provides two LangChain tools that interact with the **Notes** Notion database:
- `get_notes` — fetches all notes with `Status = Pending`
- `add_note`  — creates a new note with `Status = Pending`

Requires env vars: `NOTION_API_KEY`, `NOTION_NOTES_DB_ID`
"""

import os
import requests
from langchain.tools import tool

# ── Shared Notion request headers ─────────────────────────────────────────────
# Helper so we don't repeat header construction in every function
def _notion_headers() -> dict:
    """
    Builds the required HTTP headers for all Notion API requests.

    Returns:
        dict: Headers containing Authorization, Content-Type, and Notion-Version.
    """
    return {
        "Authorization": f"Bearer {os.getenv('NOTION_API_KEY')}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28"   # Pin to a stable Notion API version
    }


@tool
def get_notes() -> list:
    """
    Retrieves all pending notes from the Notion Notes database.

    Queries the Notion database filtered by Status == 'Pending', then
    extracts the plain-text content of each note's title property.

    Returns:
        list[str]: A list of note content strings.
                   Returns a list with a single error string on failure.
    """
    api_key = os.getenv("NOTION_API_KEY")
    db_id   = os.getenv("NOTION_NOTES_DB_ID")

    # Guard: both credentials must be present before making any API call
    if not api_key or not db_id:
        return ["Error: NOTION_API_KEY or NOTION_NOTES_DB_ID not set in environment."]

    url = f"https://api.notion.com/v1/databases/{db_id}/query"

    # Filter: only return notes that are still pending (not yet done)
    payload = {
        "filter": {
            "property": "Status",
            "select": {"equals": "Pending"}
        }
    }

    try:
        res = requests.post(url, headers=_notion_headers(), json=payload)
        res.raise_for_status()   # Raises HTTPError for 4xx/5xx responses
        data = res.json()

        notes = []
        for page in data.get("results", []):
            props = page.get("properties", {})

            # 'Note' is the title property — Notion returns it as a rich-text list
            title_list = props.get("Note", {}).get("title", [])
            note_content = (
                title_list[0].get("text", {}).get("content", "")
                if title_list else "Untitled Note"
            )
            notes.append(note_content)

        return notes

    except Exception as e:
        return [f"Error fetching notes: {str(e)}"]


@tool
def add_note(note: str) -> str:
    """
    Adds a new note to the Notion Notes database with Status = 'Pending'.

    Creates a new page in the Notion Notes database. The 'Note' property
    is used as the title and 'Status' is set to 'Pending' by default.

    Args:
        note (str): The text content of the note to be created.

    Returns:
        str: Success message with the note text, or an error message.
    """
    api_key = os.getenv("NOTION_API_KEY")
    db_id   = os.getenv("NOTION_NOTES_DB_ID")

    # Guard: both credentials must be present before making any API call
    if not api_key or not db_id:
        return "Error: NOTION_API_KEY or NOTION_NOTES_DB_ID not set in environment."

    url = "https://api.notion.com/v1/pages"

    # Notion page creation payload:
    # - parent.database_id  : which database this page belongs to
    # - properties.Note     : title field (rich-text list format)
    # - properties.Status   : select field — new notes start as 'Pending'
    payload = {
        "parent": {"database_id": db_id},
        "properties": {
            "Note": {
                "title": [{"text": {"content": note}}]
            },
            "Status": {
                "select": {"name": "Pending"}
            }
        }
    }

    try:
        res = requests.post(url, headers=_notion_headers(), json=payload)
        res.raise_for_status()
        return f"Note added successfully: {note}"

    except Exception as e:
        return f"Error adding note: {str(e)}"


# ── Quick smoke-test (uncomment to run) ───────────────────────────────────────
# print(add_note.invoke("Test note from Colab"))
# print(get_notes.invoke({}))
print("✅ Notion Notes tools defined: get_notes, add_note")

"""---
## Section 6 — Notion Calendar Tool
**Mirrors:** `tools/notion_calender.py`

Provides two LangChain tools for the **Calendar** Notion database:
- `get_calendar_events` — fetches all events for a specific date
- `add_calendar_event`  — creates a new calendar event

Requires env vars: `NOTION_API_KEY`, `NOTION_CALENDAR_DB_ID`
"""

import os
import requests
from langchain.tools import tool


@tool
def get_calendar_events(date: str) -> dict:
    """
    Retrieves all calendar events from Notion for a specific date.

    Queries the Notion Calendar database and filters results to only
    return events whose 'Date' property matches the given date exactly.

    Args:
        date (str): The date to query in ISO 8601 format (YYYY-MM-DD),
                    e.g. '2025-12-25'.

    Returns:
        dict: {"events": [{"event": str, "time": str}, ...], "date": str}
              or {"error": str} on failure.
    """
    api_key = os.getenv("NOTION_API_KEY")
    db_id   = os.getenv("NOTION_CALENDAR_DB_ID")

    # Guard: both credentials must be present
    if not api_key or not db_id:
        return {"error": "NOTION_API_KEY or NOTION_CALENDAR_DB_ID not set."}

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28"
    }

    url = f"https://api.notion.com/v1/databases/{db_id}/query"

    # Filter: match the exact date using Notion's date filter object
    payload = {
        "filter": {
            "property": "Date",
            "date": {"equals": date}
        }
    }

    try:
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        data = response.json()

        events = []
        for page in data.get("results", []):
            props = page.get("properties", {})

            # ── Extract event title ───────────────────────────────────────────
            # 'Event' is a Notion title property (rich-text list)
            event_title_list = props.get("Event", {}).get("title", [])
            event_name = (
                event_title_list[0].get("text", {}).get("content", "")
                if event_title_list else "Untitled event"
            )

            # ── Extract event time ────────────────────────────────────────────
            # 'Time' is a rich-text property (free-form HH:MM string)
            time_list = props.get("Time", {}).get("rich_text", [])
            event_time = (
                time_list[0].get("text", {}).get("content", "")
                if time_list else "All day"
            )

            events.append({"event": event_name, "time": event_time})

        return {"events": events, "date": date}

    except Exception as e:
        return {"error": str(e)}


@tool
def add_calendar_event(date: str, time: str, event: str) -> str:
    """
    Creates a new calendar event in the Notion Calendar database.

    When time is provided, the start datetime is stored as a combined
    ISO 8601 datetime string (e.g. '2025-12-25T09:00:00'). When time is
    omitted or empty, only the date is stored (all-day event).

    Args:
        date  (str): Event date in YYYY-MM-DD format.
        time  (str): Event start time in HH:MM format (24-hour),
                     or empty string for all-day events.
        event (str): Human-readable description / title of the event.

    Returns:
        str: Success message, or error message on failure.
    """
    api_key = os.getenv("NOTION_API_KEY")
    db_id   = os.getenv("NOTION_CALENDAR_DB_ID")

    # Guard: both credentials must be present
    if not api_key or not db_id:
        return "Error: NOTION_API_KEY or NOTION_CALENDAR_DB_ID not set."

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28"
    }

    url = "https://api.notion.com/v1/pages"

    # ── Compose datetime string ───────────────────────────────────────────────
    # If a time is given, combine with date for a proper datetime stamp;
    # otherwise fall back to a date-only string (all-day Notion event)
    start_datetime = f"{date}T{time}:00" if time else date

    # Notion page payload — sets Event title and the Date property
    payload = {
        "parent": {"database_id": db_id},
        "properties": {
            "Event": {
                "title": [{"text": {"content": event}}]
            },
            "Date": {
                "date": {"start": start_datetime}
            }
        }
    }

    try:
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        return f"Added event: '{event}' at {time} on {date}."

    except Exception as e:
        return f"Error adding calendar event: {str(e)}"


# ── Quick smoke-test (uncomment to run) ───────────────────────────────────────
# print(add_calendar_event.invoke({"date": "2025-12-25", "time": "09:00", "event": "Test event"}))
# print(get_calendar_events.invoke("2025-12-25"))
print("✅ Notion Calendar tools defined: get_calendar_events, add_calendar_event")

"""---
## Section 7 — Agent Intelligence Core
**Mirrors:** `agent/bot.py`

Initialises the **LangChain ReAct Agent** with:
- **LLM:** Groq-hosted `llama-3.3-70b-versatile` (fast inference)
- **Tool Belt:** weather + notes + calendar tools

The agent uses the ReAct loop:  
`Thought → Action → Observation → Thought → ... → Final Answer`
"""

# Run this first so I can see exactly what's available
import langchain, langchain_core, langchain_groq
print("langchain:", langchain.__version__)
print("langchain_core:", langchain_core.__version__)
print("langchain_groq:", langchain_groq.__version__)

# Check what's actually importable
import pkgutil
import langchain.agents as la
print("\nlangchain.agents exports:", [x for x in dir(la) if not x.startswith("_")])

import langchain_core.agents as lca
print("\nlangchain_core.agents exports:", [x for x in dir(lca) if not x.startswith("_")])

import langchain.agents as la
print(dir(la))

import os
import re
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.messages import HumanMessage

logger = get_logger("agent.bot")

REACT_PROMPT = """Answer the following questions as best you can. You have access to the following tools:

{tools}

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [{tool_names}]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: {input}
Thought:"""


def get_llm() -> ChatGroq:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise ValueError("GROQ_API_KEY is not set.")
    logger.info("Initialising Groq LLM with llama-3.3-70b-versatile")
    return ChatGroq(
        model="llama-3.3-70b-versatile",
        temperature=0.5,
        api_key=api_key
    )


class ManualReActAgent:
    """
    Hand-rolled ReAct loop that works with any LangChain-compatible LLM.
    Replaces AgentExecutor + create_react_agent which are missing in this build.
    """

    def __init__(self, llm, tools: list, max_iterations: int = 6):
        self.llm = llm
        self.tools = {t.name: t for t in tools}
        self.max_iterations = max_iterations

    def invoke(self, inputs: dict) -> dict:
        user_input = inputs["input"]
        tool_descriptions = "\n".join(
            f"{t.name}: {t.description}" for t in self.tools.values()
        )
        tool_names = ", ".join(self.tools.keys())

        prompt = REACT_PROMPT.format(
            tools=tool_descriptions,
            tool_names=tool_names,
            input=user_input
        )

        for i in range(self.max_iterations):
            response = self.llm.invoke([HumanMessage(content=prompt)])
            text = response.content
            print(text)  # verbose trace

            # ── Final Answer ──────────────────────────────────────────────────
            if "Final Answer:" in text:
                answer = text.split("Final Answer:")[-1].strip()
                return {"output": answer}

            # ── Parse Action / Action Input ───────────────────────────────────
            action_match = re.search(r"Action:\s*(.+)", text)
            action_input_match = re.search(r"Action Input:\s*(.+)", text)

            if not action_match or not action_input_match:
                # LLM didn't follow format — treat whole response as final answer
                return {"output": text.strip()}

            action = action_match.group(1).strip()
            action_input = action_input_match.group(1).strip()

            # ── Execute Tool ──────────────────────────────────────────────────
            if action not in self.tools:
                observation = f"Error: tool '{action}' not found. Available: {tool_names}"
            else:
                try:
                    observation = self.tools[action].invoke(action_input)
                except Exception as e:
                    observation = f"Error running {action}: {e}"

            # ── Append observation and loop ───────────────────────────────────
            prompt += f"{text}\nObservation: {observation}\nThought:"

        return {"output": "Max iterations reached without a final answer."}


def create_react_agent_custom() -> ManualReActAgent:
    logger.info("Creating manual ReAct agent...")
    llm = get_llm()
    tools = [
        get_weather,
        get_notes,
        add_note,
        get_calendar_events,
        add_calendar_event
    ]
    agent = ManualReActAgent(llm=llm, tools=tools)
    logger.info("ReAct agent created successfully.")
    return agent


agent = create_react_agent_custom()
print("✅ ReAct agent ready.")

"""---
## Section 8 — FastAPI Server
**Mirrors:** `api/server.py`

Defines the REST API with two endpoints:
- `POST /chat`   — accepts a user message, returns the agent's response
- `GET  /health` — simple liveness probe

The static frontend (HTML/CSS/JS) is also mounted at the root `/`.
"""

import os
import textwrap
from typing import List, Optional, Dict, Any
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse
from pydantic import BaseModel

# Reuse the logger factory from Section 3
api_logger = get_logger("api.server")

# ── FastAPI app instance ───────────────────────────────────────────────────────
app = FastAPI(
    title="Notion ReAct Planner Agent API",
    description="A reasoning-driven daily planner powered by LangChain ReAct + Notion",
    version="1.0.0"
)


# ── Request / Response schemas ─────────────────────────────────────────────────
class ChatRequest(BaseModel):
    """
    Pydantic model for the POST /chat request body.

    Attributes:
        message (str):  The user's natural-language query.
        history (list): Optional conversation history for multi-turn context.
                        Each entry is a dict with 'role' and 'content' keys.
    """
    message: str
    history: Optional[List[Dict[str, Any]]] = None


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    """
    Liveness probe endpoint.

    Returns a simple JSON object confirming the server is running.
    Used by load balancers and monitoring systems.
    """
    return {"status": "ok"}


@app.post("/chat")
async def chat(request: ChatRequest):
    """
    Main chat endpoint — passes user message to the ReAct agent and returns response.

    The agent follows the ReAct loop internally:
      Thought → (optionally) call a tool → Observation → repeat → Final Answer

    Args:
        request (ChatRequest): JSON body with 'message' and optional 'history'.

    Returns:
        dict: {"response": str} containing the agent's final answer.

    Raises:
        HTTPException 500: If the agent is not initialised or an error occurs.
    """
    global agent

    # Ensure the agent was successfully initialised at startup
    if not agent:
        raise HTTPException(status_code=500, detail="Agent not initialised.")

    try:
        api_logger.info(f"Received message: {request.message[:80]}")

        # Invoke the AgentExecutor — the input key must match the prompt variable
        response = agent.invoke({"input": request.message})

        # AgentExecutor returns a dict with 'output' key for the final answer
        return {"response": response.get("output", "No response generated.")}

    except Exception as e:
        api_logger.error(f"Error during chat: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ── Inline static frontend ─────────────────────────────────────────────────────
# In the full project the static/ folder is mounted; here we serve
# a minimal inline HTML chat UI so the notebook is self-contained.

CHAT_HTML = textwrap.dedent("""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Smart Planner</title>
  <style>
    body { font-family: sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; }
    #chat { border: 1px solid #ddd; border-radius: 8px; height: 400px; overflow-y: auto;
            padding: 16px; background: #f9f9f9; margin-bottom: 12px; }
    .user { text-align: right; margin: 8px 0; }
    .agent { text-align: left; margin: 8px 0; }
    .bubble { display: inline-block; padding: 8px 14px; border-radius: 18px; max-width: 80%; }
    .user .bubble { background: #0084ff; color: #fff; }
    .agent .bubble { background: #e4e4e4; color: #111; }
    #controls { display: flex; gap: 8px; }
    #msg { flex: 1; padding: 10px; border-radius: 6px; border: 1px solid #ccc; font-size: 15px; }
    button { padding: 10px 18px; border-radius: 6px; background: #0084ff;
             color: #fff; border: none; cursor: pointer; font-size: 15px; }
  </style>
</head>
<body>
  <h2>🤖 Smart Planner Assistant</h2>
  <div id="chat"></div>
  <div id="controls">
    <input id="msg" placeholder="Type a message..." />
    <button onclick="send()">Send</button>
  </div>
  <script>
    const chat = document.getElementById('chat');
    const input = document.getElementById('msg');
    function addMsg(role, text) {
      const d = document.createElement('div');
      d.className = role;
      d.innerHTML = `<span class="bubble">${text}</span>`;
      chat.appendChild(d); chat.scrollTop = chat.scrollHeight;
    }
    async function send() {
      const msg = input.value.trim(); if (!msg) return;
      addMsg('user', msg); input.value = '';
      const res = await fetch('/chat', { method:'POST',
        headers:{'Content-Type':'application/json'},
        body: JSON.stringify({message: msg}) });
      const data = await res.json();
      addMsg('agent', data.response || data.detail);
    }
    input.addEventListener('keydown', e => { if (e.key === 'Enter') send(); });
  </script>
</body></html>
""")

@app.get("/", response_class=HTMLResponse)
async def root():
    """Serve the inline chat UI at the root URL."""
    return CHAT_HTML


api_logger.info("✅ FastAPI app defined with /chat and /health endpoints.")
print("✅ FastAPI server code ready.")

"""---
## Section 9 — Notion Database Setup Script
**Mirrors:** `scripts/setup_notion_databases.py`

Run this **once** to automatically create the two Notion databases  
(Calendar + Notes) inside a parent Notion page you choose.

After running, copy the printed database IDs into Colab Secrets as  
`NOTION_CALENDAR_DB_ID` and `NOTION_NOTES_DB_ID`.
"""

import os
import re
import requests


def extract_page_id(input_str: str) -> str:
    """
    Extracts a clean 32-character Notion page ID from a URL or raw ID string.

    Handles formats like:
      - Full URL: https://www.notion.so/My-Page-1234567890abcdef1234567890abcdef
      - URL with query params: ...?v=...
      - Raw UUID with dashes: 12345678-90ab-cdef-1234-567890abcdef
      - Raw 32-char hex string: 1234567890abcdef1234567890abcdef

    Args:
        input_str (str): The user-provided page URL or ID string.

    Returns:
        str: 32-character hex page ID (dashes removed).
    """
    # Strip query parameters from the URL if present
    if "?" in input_str:
        input_str = input_str.split("?")[0]

    if "notion.so" in input_str:
        # Extract the last path segment and find the 32-char hex ID within it
        parts = input_str.split("/")
        last_part = parts[-1]
        match = re.search(r'([a-fA-F0-9]{32})', last_part)
        if match:
            return match.group(1)
        return last_part  # Fall back to raw last segment

    # Remove dashes from UUID format
    return input_str.replace("-", "")


def create_databases(parent_page_url_or_id: str = None):
    """
    Creates the two Notion databases required by the Smart Planner:
      1. 'Smart Task Planner Calendar' — for scheduling events
      2. 'Smart Task Planner Notes'    — for storing reminders/notes

    Both databases are created as children of the specified parent Notion page.
    The parent page must already exist and must have the integration connected
    (Notion page → ... → Add connections → select your integration).

    Args:
        parent_page_url_or_id (str, optional):
            The parent page URL or 32-char page ID.
            If None, the function will prompt for it interactively.

    Prints:
        The database IDs to copy into Colab Secrets / .env.
    """
    api_key = os.getenv("NOTION_API_KEY")

    print("\n─── Notion Database Setup ───")

    if not api_key:
        print("❌ NOTION_API_KEY not found. Please set it in Colab Secrets (Section 1).")
        return

    print(f"✅ Using API Key: {api_key[:6]}...{api_key[-4:]}")

    # ── Get parent page ID ────────────────────────────────────────────────────
    if not parent_page_url_or_id:
        print("\nTo create databases you need a parent Notion page:")
        print("  1. Create a page in Notion (e.g. 'Smart Task Planner').")
        print("  2. Share it with your integration (... → Add connections).")
        print("  3. Copy the page URL or ID from the browser address bar.")
        parent_page_url_or_id = input("\nEnter Parent Page URL or ID: ").strip()

    parent_page_id = extract_page_id(parent_page_url_or_id)

    if len(parent_page_id) != 32:
        print(f"⚠️  ID '{parent_page_id}' is not 32 chars — proceeding anyway...")

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28"
    }

    # ── Create Calendar database ──────────────────────────────────────────────
    print("\nCreating 'Smart Task Planner Calendar' database...")
    calendar_payload = {
        "parent": {"type": "page_id", "page_id": parent_page_id},
        "title": [{"type": "text", "text": {"content": "Smart Task Planner Calendar"}}],
        "properties": {
            "Event":  {"title": {}},    # Primary title property
            "Date":   {"date": {}},     # Date/datetime for the event
            "Time":   {"rich_text": {}},# Free-form time string (HH:MM)
            "Status": {
                "select": {
                    "options": [
                        {"name": "Upcoming",  "color": "blue"},
                        {"name": "Done",      "color": "green"},
                        {"name": "Cancelled", "color": "red"}
                    ]
                }
            }
        }
    }

    cal_db_id = None
    try:
        res = requests.post("https://api.notion.com/v1/databases",
                            headers=headers, json=calendar_payload)
        if res.status_code == 200:
            cal_db_id = res.json()["id"]
            print(f"   ✅ Calendar DB created! ID: {cal_db_id}")
        else:
            print(f"   ❌ Failed: {res.text}")
    except Exception as e:
        print(f"   ❌ Exception: {e}")

    # ── Create Notes database ─────────────────────────────────────────────────
    print("\nCreating 'Smart Task Planner Notes' database...")
    notes_payload = {
        "parent": {"type": "page_id", "page_id": parent_page_id},
        "title": [{"type": "text", "text": {"content": "Smart Task Planner Notes"}}],
        "properties": {
            "Note":   {"title": {}},    # Primary title property
            "Status": {
                "select": {
                    "options": [
                        {"name": "Pending", "color": "yellow"},
                        {"name": "Done",    "color": "green"}
                    ]
                }
            }
        }
    }

    notes_db_id = None
    try:
        res = requests.post("https://api.notion.com/v1/databases",
                            headers=headers, json=notes_payload)
        if res.status_code == 200:
            notes_db_id = res.json()["id"]
            print(f"   ✅ Notes DB created! ID: {notes_db_id}")
        else:
            print(f"   ❌ Failed: {res.text}")
    except Exception as e:
        print(f"   ❌ Exception: {e}")

    # ── Summary ───────────────────────────────────────────────────────────────
    print("\n─── Setup Complete ───")
    if cal_db_id and notes_db_id:
        print("Copy these values into Colab Secrets (or .env for local use):")
        print(f"  NOTION_CALENDAR_DB_ID = {cal_db_id}")
        print(f"  NOTION_NOTES_DB_ID    = {notes_db_id}")
        print("\nThen re-run Section 1 to reload the environment variables.")


# ── Uncomment the line below and provide your Notion parent page URL to run ───
# create_databases("https://www.notion.so/Your-Page-Title-<32charID>")
print("ℹ️  Notion DB setup function defined. Uncomment the last line to run it.")

"""---
## Section 10 — Agent Testing
**Mirrors:** `scripts/test_agent.py`

Direct agent invocation tests — no HTTP layer, exercises the tool belt end-to-end.
"""

# ── Test 1: Weather query ──────────────────────────────────────────────────────
# Verifies that the agent can geocode a city and fetch its temperature.

print("=" * 60)
print("TEST 1: Weather Query")
print("=" * 60)

response_1 = agent.invoke({"input": "What is the current temperature in Delhi?"})
print("\n🤖 Agent Response:", response_1["output"])

# ── Test 2: Add a note ─────────────────────────────────────────────────────────
# Verifies that the agent can create a new Pending note in Notion.

print("=" * 60)
print("TEST 2: Add a Note to Notion")
print("=" * 60)

response_2 = agent.invoke({"input": "Add a note: buy groceries tomorrow morning"})
print("\n🤖 Agent Response:", response_2["output"])

# ── Test 3: Get pending notes ──────────────────────────────────────────────────
# Verifies retrieval of all Pending notes from the Notion Notes database.

print("=" * 60)
print("TEST 3: Get Pending Notes from Notion")
print("=" * 60)

response_3 = agent.invoke({"input": "What are my pending notes?"})
print("\n🤖 Agent Response:", response_3["output"])

# ── Test 4: Add a calendar event ───────────────────────────────────────────────
# Verifies that the agent can schedule a new event in the Notion Calendar database.

print("=" * 60)
print("TEST 4: Add a Calendar Event")
print("=" * 60)

from datetime import date
today = date.today().isoformat()  # Use today's real date dynamically

response_4 = agent.invoke({
    "input": f"Schedule a 30-minute morning walk at 7:00 AM on {today}"
})
print("\n🤖 Agent Response:", response_4["output"])

# ── Test 5: Multi-tool planning query ─────────────────────────────────────────
# The showcase test: the agent must use weather + notes + calendar in one response.
# This mirrors the demo shown in the project screenshots.

print("=" * 60)
print("TEST 5: Multi-tool Planning Query")
print("=" * 60)

from datetime import date, timedelta
tomorrow = (date.today() + timedelta(days=1)).isoformat()

response_5 = agent.invoke({
    "input": (
        f"Plan my {tomorrow} morning. Check the weather in Delhi, "
        "add a note to remind me to carry an umbrella if it might rain, "
        "and schedule a 30-minute walk at 8 AM if the weather is good."
    )
})
print("\n🤖 Agent Response:", response_5["output"])

"""---
## Section 11 — Run the Server (ngrok tunnel)
**Mirrors:** `main.py`

Starts the FastAPI server on port 8000 and exposes it via a public ngrok URL.

> **Note:** Set your ngrok authtoken once:  
> `!ngrok authtoken <your_token>` — or add `NGROK_AUTHTOKEN` to Colab Secrets.

The server runs in a background thread so the notebook cell doesn't block.
"""

import threading
import uvicorn
from pyngrok import ngrok, conf

# ── Ngrok authentication ───────────────────────────────────────────────────────
# Set your ngrok authtoken so tunnels can be created.
# Get a free token at: https://dashboard.ngrok.com/get-started/your-authtoken
try:
    ngrok_token = userdata.get('NGROK_AUTHTOKEN')
    conf.get_default().auth_token = ngrok_token
    print("✅ ngrok authtoken loaded from Colab Secrets.")
except Exception:
    print("⚠️  NGROK_AUTHTOKEN not in Colab Secrets — add it or run:")
    print("   !ngrok authtoken <your_token>")


def run_server():
    """
    Starts the Uvicorn ASGI server for the FastAPI app in a daemon thread.

    Running in a daemon thread means the server is automatically stopped
    when the Colab runtime shuts down.
    """
    uvicorn.run(
        app,             # The FastAPI app defined in Section 8
        host="0.0.0.0",  # Bind to all interfaces so ngrok can reach it
        port=8000,
        log_level="info"
    )


# ── Start server in background thread ─────────────────────────────────────────
server_thread = threading.Thread(target=run_server, daemon=True)
server_thread.start()

# ── Open ngrok tunnel → public HTTPS URL ──────────────────────────────────────
# ngrok forwards traffic from a public URL to localhost:8000
public_url = ngrok.connect(8000)

print("\n" + "=" * 60)
print("🚀 Notion ReAct Planner Agent is LIVE!")
print("=" * 60)
print(f"🌐 Public URL : {public_url}")
print(f"💬 Chat UI   : {public_url}")
print(f"❤️  Health    : {public_url}/health")
print(f"📖 API docs  : {public_url}/docs")
print("=" * 60)
print("\nOpen the Public URL above in your browser to use the chat interface.")
print("The server runs until this Colab session ends.")

"""---
## Section 12 — MLflow Experiment Tracking (Optional)

Log agent interactions as MLflow runs to track queries, responses, and latency
on DagsHub (or locally). Useful for iterating on prompts and monitoring quality.
"""

import mlflow
import time

# ── Point MLflow to the tracking server configured in Section 1 ───────────────
mlflow.set_tracking_uri(os.environ['MLFLOW_TRACKING_URI'])

# ── DagsHub authentication (only needed for remote tracking) ──────────────────
if USE_DAGSHUB:
    import dagshub
    # dagshub.init reads MLFLOW_TRACKING_USERNAME and MLFLOW_TRACKING_PASSWORD
    # from the environment to authenticate with the DagsHub MLflow server.
    dagshub.init(
        repo_owner=os.environ['MLFLOW_TRACKING_USERNAME'],
        repo_name="notion-react-agent",  # Replace with your DagsHub repo name
        mlflow=True
    )

# ── Create or load an experiment ──────────────────────────────────────────────
mlflow.set_experiment("notion-react-planner")


def log_agent_run(query: str, response: str, latency_ms: float):
    """
    Logs a single agent interaction as an MLflow run.

    Records:
      - Parameters : the input query
      - Metrics    : response latency in milliseconds
      - Tags       : model name and agent type for filtering

    Args:
        query      (str):   The user's input message.
        response   (str):   The agent's final answer.
        latency_ms (float): Wall-clock time taken by the agent in milliseconds.
    """
    with mlflow.start_run():
        mlflow.log_param("query", query[:250])        # Truncate long queries
        mlflow.log_param("response", response[:500])  # Truncate long responses
        mlflow.log_metric("latency_ms", latency_ms)
        mlflow.set_tag("model", "llama-3.3-70b-versatile")
        mlflow.set_tag("agent_type", "ReAct")


# ── Example: log a timed agent invocation ─────────────────────────────────────
test_query = "What is the weather in Mumbai right now?"

start_time = time.time()
result = agent.invoke({"input": test_query})
elapsed_ms = (time.time() - start_time) * 1000

log_agent_run(
    query=test_query,
    response=result["output"],
    latency_ms=elapsed_ms
)

print(f"\n✅ Run logged to MLflow.")
print(f"   Query    : {test_query}")
print(f"   Response : {result['output']}")
print(f"   Latency  : {elapsed_ms:.0f} ms")

import zipfile
import os

# ── Save all outputs and zip them ─────────────────────────────────────────────
output_dir = "/content/agent_outputs"
os.makedirs(output_dir, exist_ok=True)

# Collect all test responses
outputs = {
    "test1_weather.txt":        response_1["output"],
    "test2_add_note.txt":       response_2["output"],
    "test3_get_notes.txt":      response_3["output"],
    "test4_calendar_event.txt": response_4["output"],
    "test5_multi_tool.txt":     response_5["output"],
}

# Write each output to a file
for filename, content in outputs.items():
    with open(os.path.join(output_dir, filename), "w") as f:
        f.write(content)

# Zip everything
zip_path = "/content/agent_outputs.zip"
with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
    for filename in outputs:
        zf.write(os.path.join(output_dir, filename), arcname=filename)

print(f"✅ All outputs saved and zipped → {zip_path}")

# ── Download in Colab ──────────────────────────────────────────────────────────
from google.colab import files
files.download(zip_path)